// =====================================================================
// ICON RESOLVER — maps string icon names (from module catalog) to Lucide components.
// Central registry so navigation never imports all icons eagerly.
// =====================================================================

import {
  LayoutDashboard,
  Gauge,
  Settings,
  Boxes,
  Users,
  ShieldCheck,
  ScrollText,
  UserCircle,
  Package,
  UserPlus,
  KeyRound,
  Radio,
  History,
  Server,
  FileKey,
  Settings2,
  Network,
  Share2,
  GitBranch,
  Globe,
  Cable,
  Shield,
  Layers,
  Flame,
  Clock,
  Activity,
  TrendingUp,
  BarChart3,
  Bell,
  HeartPulse,
  FileText,
  ReceiptText,
  Play,
  Ticket,
  CreditCard,
  CircleDollarSign,
  Plug,
  Scale,
  Wrench,
  MessageSquareWarning,
  HardHat,
  Hammer,
  AlertTriangle,
  Landmark,
  DollarSign,
  Wallet,
  Receipt,
  Router,
  Cpu,
  MessageSquare,
  Sparkles,
  Bot,
  Stethoscope,
  TrendingDown,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Gauge,
  Settings,
  Boxes,
  Users,
  ShieldCheck,
  ScrollText,
  UserCircle,
  Package,
  UserPlus,
  KeyRound,
  Radio,
  History,
  Server,
  FileKey,
  Settings2,
  Network,
  Subnet: Share2, // alias — Subnet doesn't exist in lucide
  Share2,
  GitBranch,
  Globe,
  Cable,
  Shield,
  Layers,
  Flame,
  Clock,
  Activity,
  TrendingUp,
  BarChart3,
  Bell,
  Pulse: HeartPulse, // alias
  HeartPulse,
  FileText,
  ReceiptText,
  Play,
  Ticket,
  CreditCard,
  CircleDollarSign,
  Plug,
  Scale,
  Wrench,
  MessageSquareWarning,
  HardHat,
  Hammer,
  AlertTriangle,
  Landmark,
  DollarSign,
  Wallet,
  Receipt,
  Router,
  Cpu,
  MessageSquare,
  Sparkles,
  Bot,
  Stethoscope,
  TrendingDown,
};

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? Gauge;
}
